### ISSUE TITLE
Add replace-all option avoiding delete not mached key

### ISSUE THREAD

**Issue by f-laino** [Langsdorf/env-replace#6]
Use `replace-all` argument the rows with not matched keys are removed.

**Comment by Langsdorf** [comment]
Hi @f-laino! Please, checkout the [new version 1.1.7](https://github.com/Langsdorf/env-replace/pull/7)

Added `remove-non-matches` option (default as false):

```yaml
# Initial .env file:
# API_URL=https://api.example.com
# API_KEY=123456
uses: Langsdorf/env-replace@v1.1.7
with:
  replace-all: |
    API_URL=https://api.staging.example.com
    SECRET_VALUE=${{ secrets.SECRET_VALUE }}
  upsert: true
  remove-non-matches: false
# Resulting .env file:
# API_URL=https://api.staging.example
# API_KEY=123456
# SECRET_VALUE=${{ secrets.SECRET_VALUE }}
```
