### ISSUE TITLE
Add an option to differentiate between input file and output file

### ISSUE THREAD

**Issue by f-laino** [Langsdorf/env-replace#8]
Something like `output` in case, for example, you had to create `.env` from `.env.example`

**Comment by Langsdorf** [comment]
Hi, @f-laino!

Please, checkout the release v1.2.7

Added the 'output' option. The 'file' option act as 'input'.
Didn't change the name because it might break something.

```yml
    - uses: Langsdorf/env-replace@v1.2.7
        with:
          key: "HELLO"
          value: "TEST"
          file: "./src/tests/.env"
          output: "./src/tests/.env.out"
      - run: |
          cat ./src/tests/.env.out | grep "TEST"
```
